version: '3'
services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ecompwd
      POSTGRES_USER: ecomuser
      POSTGRES_DB: ecom
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    volumes:
      - memdb:/data
  backend:
    build: ./backend/
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    volumes:
      - ./backend/:/app
      - /app/node_modules/
    command: npm run migrate && npm run seed && npm run dev
volumes:
 dbdata:
 memdb: