version: '3'
services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ecompwd
      POSTGRES_USER: ecomuser
      POSTGRES_DB: ecom
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    volumes:
      - memdb:/data
  backend:
    build: ./backend/
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile.prod
    ports:
      - 8000:3000
    depends_on:
      - backend
volumes:
 dbdata:
 memdb: