version: '3'
services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ecompwd
      POSTGRES_USER: ecomuser
      POSTGRES_DB: ecom
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    volumes:
      - memdb:/data
    ports:
      - 6379:6379
volumes:
 dbdata:
 memdb: