version: '3'
services:
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ecompwd
      POSTGRES_USER: ecomuser
      POSTGRES_DB: ecom
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend/
    ports:
      - 8001:8000
    depends_on:
      - db
    volumes:
      - ./backend/:/app
    command: npm run migrate && npm run dev
  frontend:
    build: ./frontend/
    ports:
      - 8000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend/:/app
    command: npm run start
volumes:
 dbdata: